### ISSUE TITLE
Terraform always wants to recreate new instances

### ISSUE THREAD

**Issue by dradtke** [squat/terraform-provider-vultr#16]
Each time I plan, Terraform wants to recreate the instance that I already have, even if there haven't been any changes to it. The relevant line in the output is:

```
id:                   "11884440" => <computed> (forces new resource)
```

I guess since the ID isn't specified in the input files, Terraform always detects this as something that needs to be updated, and so an apply will always destroy the instance and create a new one.

If I have time in the coming weeks I can try to get a PR for this, but it would take some time becoming familiar with the source and looking into how other providers handle this.

**Comment by squat** [comment]
This is not expected behavior. On the other hand, you should never have to manually specify the id of any object in Terraform (unless you are importing existing infrastructure); the ID is supposed to be stored in your tfstate file so that terraform can keep track of infrastructure state between invocations. Can you please share your Terraform configuration or provide a minimal example that reproduces the issue so I can validate the problem?

Thanks for filing @dradtke

**Comment by dradtke** [comment]
Huh, I'm having trouble reproducing it now. My hunch was that it was caused by using snapshots, but now I'm having trouble recreating the issue. I'll close this and re-open if I manage to get a reliable test case.

**Comment by squat** [comment]
Sounds like a plan
