### ISSUE TITLE
Windows Binaries?

### ISSUE THREAD

**Issue by atif089** [squat/terraform-provider-vultr#36]
Hi,

Can you please provide Windows Binaries please? I'm a noob and I don't know how to compile Go on Windows.

**Comment by squat** [comment]
Hi @atif089, thanks for bringing this up. I'm glad to see windows users are also interested in this project. I built a windows binary for a v0.1.4 release candidate but I have no windows machine to test it on. Can you test it to see that the binary works as expected for you? If it does, I'll merge the changes.
[terraform-provider-vultr_v0.1.4-rc1_windows_amd64.tar.gz](https://github.com/squat/terraform-provider-vultr/files/2038890/terraform-provider-vultr_v0.1.4-rc1_windows_amd64.tar.gz)

**Comment by atif089** [comment]
@squat Thanks for quick response. This worked great for the first time! I think there is a small issue due to Vultr's restrictions with IP Address due to which it's not working anymore.

I removed the assigned IPv4s manually and I now get the following error regardless of what command I write (destroy/apply/plan)

```
data.vultr_plan.starter: Refreshing state...
vultr_instance.example: Refreshing state... (ID: 15906180)
vultr_ipv4.example[1]: Refreshing state... (ID: 15906180/149.28.193.170)
vultr_ipv4.example[0]: Refreshing state... (ID: 15906180/149.28.193.98)

Error: Error refreshing state: 1 error(s) occurred:

* vultr_ipv4.example: 2 error(s) occurred:

* vultr_ipv4.example[1]: vultr_ipv4.example.1: Error getting IPv4 addresses: Invalid server.  Check SUBID value and ensure your API key matches the server's account
* vultr_ipv4.example[0]: vultr_ipv4.example.0: Error getting IPv4 addresses: Invalid server.  Check SUBID value and ensure your API key matches the server's account
```

I'm using the `basic/example.tf` configuration from the examples section.

**Comment by squat** [comment]
@atif089 ok great. I'll promote the release candidate to a full release then.

Ok so if I understand correctly:
* you `terraform apply`'d the configuration in examples/basic and this worked well
* in the console you manually delete the IPv4s
* `terraform plan` returns errors now?

In general it is bad practice to mix the management of resources. They should be either all manual or all terraform. That said, the provider should be able to automatically recover if certain resources are missing. Let me try to reproduce

**Comment by squat** [comment]
@atif089 I don't think that that is the cause of the error. From the logs you are showing me, it seems that the provider is crashing while it is refreshing the state, meaning that it wasn't yet attempting to delete anything, only read state from the API.

The underlying cause here is that the _server_ to which the IPs were connected is gone. Due to the fact that IPv4s must be connected to a server, if the server is gone, there is no way to find the IPv4s. Did you happen to delete the server outside of Terraform. That is the only explanation here.

In fact, I am able to replicate identical logs to yours if I follow a slightly different flow:
* `terraform apply` the configuration in examples/basic
* __in the console manually delete the *server*__
* `terraform plan` returns

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

vultr_ssh_key.squat: Refreshing state... (ID: 5b08fad750f26)
data.vultr_region.silicon_valley: Refreshing state...
vultr_firewall_group.example: Refreshing state... (ID: 3f12bdad)
data.vultr_os.container_linux: Refreshing state...
data.vultr_plan.starter: Refreshing state...
vultr_firewall_rule.ssh: Refreshing state... (ID: 3f12bdad/2)
vultr_firewall_rule.icmp: Refreshing state... (ID: 3f12bdad/1)
vultr_instance.example: Refreshing state... (ID: 15920658)
vultr_ipv4.example[0]: Refreshing state... (ID: 15920658/149.28.194.122)
vultr_ipv4.example[1]: Refreshing state... (ID: 15920658/45.32.135.205)

Error: Error refreshing state: 1 error(s) occurred:

* vultr_ipv4.example: 2 error(s) occurred:

* vultr_ipv4.example[1]: vultr_ipv4.example.1: Error getting IPv4 addresses: Invalid server.  Check SUBID value and ensure your API key matches the server's
account
* vultr_ipv4.example[0]: vultr_ipv4.example.0: Error getting IPv4 addresses: Invalid server.  Check SUBID value and ensure your API key matches the server's
account
```

This looks identical to the error you posted. I strongly suspect that this is what you did, as it matches the results but more importantly is the only real explanation for the behavior.

When you delete a server, you also delete the IPv4s that were attached to it, so the fix here is to patch the provider so that it knows the IPv4s are gone when the server was deleted. I'll post a fix shortly. Please test it and re-open this issue if it doesn't solve the problem. If that happens, please post the full Terraform logs to help me debug.

**Comment by atif089** [comment]
Yes I did manually delete the server outside.

**Comment by atif089** [comment]
I also deleted the tfstate file and tried but the error persisted.

**Comment by squat** [comment]
@atif089 thanks for verifying that. Would you mind testing that flow with https://github.com/squat/terraform-provider-vultr/releases/tag/v0.1.5-rc.1 and letting me know if you still repro the bug?

**Comment by atif089** [comment]
@squat Works Great!
