### ISSUE TITLE
coreos provisioning

### ISSUE THREAD

**Issue by 2color** [squat/terraform-provider-vultr#7]
I've been using the provider for a couple of days and it's working well.

Normally, CoreOS is provisioned with either **coreos-cloudinit** or **Ignition**

What is the recommended way to do that with Vultr?

**Comment by squat** [comment]
@2color unfortunately, Vultr is not an officially supported cloud provider for Ignition [1]. This means that there are only two real options for provisioning Container Linux:
1. Use coreos-cloudinit directly by leveraging the `user_data` field on the `vultr_instance` resource object; or
2. Use a custom IPXE script to PXE boot Container Linux and supply the necessary kernel parameters to point ignition to the Vultr's metadata service's user-data endpoint [2]

The former is easy to use since you only need to write a conforming cloud-config file and supply it to the `user-data` field; Vultr takes care of the rest. The latter is more powerful since you can leverage all the features of the far superior Ignition provisioning system. However, it is also considerably more complex since Vultr does not have proper Ignition support; the process ends up being similar to booting a bare-metal server with Ignition. Please look over the Kubernetes example for a complete 

[1] https://github.com/coreos/ignition/tree/master/internal/providers
[2] https://github.com/squat/terraform-provider-vultr/blob/master/examples/kubernetes/resources/ipxe

**Comment by squat** [comment]
Please re-open if you have any more questions.

**Comment by 2color** [comment]
Thanks for the insightful answer. 

P.s. awesome that you added the Kubernetes example!
